apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligent-train-env
  namespace: {{ .Values.namespace }}
data:
  MQTT_BROKER: "mosquitto"
  MQTT_PORT: "1883"
  MQTT_TOPIC: "train-image"
  MQTT_PUB_TOPIC: "train-model-result"
  MODEL_PATH: models/model.onnx
  MIN_CONF_THRESHOLD: "0.6"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: intelligent-train
    app.kubernetes.io/component: intelligent-train
    app.kubernetes.io/instance: intelligent-train
    app.kubernetes.io/name: intelligent-train
    app.kubernetes.io/part-of: train
  name: intelligent-train
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: intelligent-train
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: intelligent-train
        deployment: intelligent-train
    spec:
      containers:
      - image: {{ include "image" (dict "Values" .Values "name" "intelligentTrain") | quote }}
        imagePullPolicy: {{ include "imagePullPolicy" (dict "Values" .Values "name" "intelligentTrain") | quote }}
        name: intelligent-train
        envFrom:
        - configMapRef:
            name: intelligent-train-env
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      serviceAccountName: train
      serviceAccount: train
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: "rivieradev2024-crazytrain.netlify.app/arm64-architecture"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/arch: arm64
