apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/route-disabled: "false"
  labels:
    app: monitoring-app
    app.kubernetes.io/component: monitoring-app
    app.kubernetes.io/instance: monitoring-app
    app.kubernetes.io/name: monitoring-app
    app.kubernetes.io/part-of: monitoring-app
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-namespace: monitoring-app
  name: monitoring-app
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: monitoring-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: monitoring-app
        deployment: monitoring-app
    spec:
      containers:
      - image: {{ include "image" (dict "Values" .Values "name" "monitoringApp") | quote }}
        imagePullPolicy: {{ include "imagePullPolicy" (dict "Values" .Values "name" "monitoringApp") | quote }}
        name: monitoring-app
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: KAFKA_TOPIC_MONITORING_NAME
          value: train-monitoring
        - name: KAFKA_TOPIC_COMMAND_CAPTURE_NAME
          value: train-command-capture      
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring-app
    app.kubernetes.io/component: monitoring-app
    app.kubernetes.io/instance: monitoring-app
    app.kubernetes.io/name: monitoring-app
    app.kubernetes.io/part-of: monitoring-app
    app.openshift.io/runtime-version: latest
  name: monitoring-app
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
  - name: 8443-tcp
    port: 8443
  selector:
    app: monitoring-app
    deployment: monitoring-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: monitoring-app
    app.kubernetes.io/component: monitoring-app
    app.kubernetes.io/instance: monitoring-app
    app.kubernetes.io/name: monitoring-app
    app.kubernetes.io/part-of: monitoring-app
    app.openshift.io/runtime-version: latest
  name: monitoring-app
  namespace: {{ .Values.namespace }}
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: monitoring-app
    weight: 100
  wildcardPolicy: None