apiVersion: v1
kind: ConfigMap
metadata:
  name: train-controller-env
data:
  LEGO_BACKEND: mock
  DEBUG: main,lego-gear-mock
  MQTT_BROKER_URL: mqtt://mosquitto:1883
  MQTT_TOPIC: train-command
  LEGO_MOTOR_FULL_POWER: "80"
  LEGO_MOTOR_LOW_POWER: "65"
  LEGO_SLEEP_TIME: "1000"
  LEGO_RAMPUP_TIME: "4000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train-controller
    app.kubernetes.io/component: train-controller
    app.kubernetes.io/instance: train-controller
    app.kubernetes.io/name: train-controller
    app.kubernetes.io/part-of: train
  name: train-controller
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: train-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: train-controller
        deployment: train-controller
    spec:
      containers:
      - image: {{ include "image" (dict "Values" .Values "name" "trainController") | quote }}
        imagePullPolicy: {{ include "imagePullPolicy" (dict "Values" .Values "name" "trainController") | quote }}
        name: train-controller
        envFrom:
        - configMapRef:
            name: train-controller-env
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      serviceAccountName: train
      serviceAccount: train
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
