apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildbot-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildbot-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildbot-scc
subjects:
- kind: ServiceAccount
  name: buildbot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildbot-can-push
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: buildbot
